# Generated by Django 5.2.17 on 2026-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category_ar', models.CharField(max_length=100)),
                ('category_en', models.CharField(max_length=100)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('excerpt_ar', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('body_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('read_time_ar', models.CharField(max_length=50)),
                ('read_time_en', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
