# Generated by Django 5.2.17 on 2026-10-08 15:24

import accounts.phone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text="The academy's WhatsApp number. Leave empty to hide the floating button.", max_length=30, validators=[accounts.phone.validate_whatsapp])),
                ('whatsapp_message', models.CharField(blank=True, help_text="Optional text pre-filled in the visitor's chat.", max_length=200)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
