# Generated by Django 5.2.17 on 2026-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='features_group_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_group_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_private_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_private_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_semi_private_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_semi_private_en',
            field=models.TextField(blank=True),
        ),
    ]
