# Generated by Django 5.2.17 on 2026-09-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_owner', models.BooleanField(default=False)),
                ('name_ar', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('role_ar', models.CharField(max_length=150)),
                ('role_en', models.CharField(max_length=150)),
                ('specialties_ar', models.TextField(blank=True)),
                ('specialties_en', models.TextField(blank=True)),
                ('bio_ar', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_owner', 'order', 'created_at'],
            },
        ),
    ]
