# Generated by Django 5.2.17 on 2026-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
