# Generated by Django 5.2.17 on 2026-09-29 17:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_optional_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('student_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, upload_to='team/reviews/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='team.teammember')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
