# Generated by Django 5.2.17 on 2026-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tag_ar', models.CharField(help_text='e.g. قواعد / Grammar', max_length=100)),
                ('tag_en', models.CharField(max_length=100)),
                ('passage_ar', models.TextField(blank=True, help_text='Reading passage, if this is a reading question')),
                ('passage_en', models.TextField(blank=True)),
                ('audio_label_ar', models.CharField(blank=True, help_text='Label shown for listening questions', max_length=200)),
                ('audio_label_en', models.CharField(blank=True, max_length=200)),
                ('text_ar', models.TextField()),
                ('text_en', models.TextField()),
                ('options_ar', models.JSONField(help_text='List of 4 answer strings')),
                ('options_en', models.JSONField(help_text='List of 4 answer strings')),
                ('correct_index', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
