# Generated by Django 5.2.17 on 2026-09-24 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio clip for listening questions', upload_to='quiz/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'ogg', 'oga', 'm4a', 'aac', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='options_ar',
            field=models.JSONField(help_text='List of answer strings'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options_en',
            field=models.JSONField(blank=True, default=list, help_text='List of answer strings (optional; falls back to Arabic)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_en',
            field=models.TextField(blank=True),
        ),
    ]
