# Generated by Django 5.2.17 on 2026-09-24 15:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_audio_file_optional_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_mode', models.CharField(choices=[('per_question', 'درجة لكل سؤال'), ('total', 'درجة كلية للاختبار')], default='total', max_length=20)),
                ('total_marks', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Whole-test marks, split equally across questions (total mode)', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
            ],
            options={
                'verbose_name': 'Quiz settings',
                'verbose_name_plural': 'Quiz settings',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Marks for this question (used when grading per question)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
