# Generated by Django 5.2.17 on 2026-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds allowed for this question. Empty = use the default from quiz settings.', null=True),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='exam_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Time limit for the whole test in minutes (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='quizsettings',
            name='question_time_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Default time per question in seconds (0 = no limit)'),
        ),
    ]
