# Generated by Django 5.2.17 on 2026-10-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_placementresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementresult',
            name='level',
        ),
    ]
