# Generated by Django 5.2.17 on 2026-09-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('content_staff', 'موظف محتوى'), ('teacher', 'مدرّس')], max_length=20),
        ),
    ]
