# Generated by Django 5.2.17 on 2026-10-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'مدير'), ('content_staff', 'مشرف المحتوى'), ('support', 'مسؤول خدمة العملاء'), ('teacher', 'مدرّس')], max_length=20),
        ),
    ]
