# Generated by Django 5.2.17 on 2026-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(choices=[('students', 'طلاب / أشخاص عاديون'), ('teachers', 'مدرّسون')], default='students', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='offers_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='offers_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_group',
            field=models.PositiveIntegerField(blank=True, help_text="EGP; empty = use the level's price", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price_private',
            field=models.PositiveIntegerField(blank=True, help_text="EGP; empty = use the level's price", null=True),
        ),
    ]
