# Generated by Django 5.2.17 on 2026-10-02 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def clear_course_level_schedule(apps, schema_editor):
    """Sessions used to belong to the course; they now belong to a cohort (group / private student).

    Nothing was in use when this changed, so old sessions and weekly slots are dropped
    rather than guessed into a cohort.
    """
    for name in ("Attendance", "LessonAttachment", "Lesson", "CourseSlot"):
        apps.get_model("courses", name).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_audience_course_offers_group_and_more'),
        ('team', '0003_teamreview'),
    ]

    operations = [
        migrations.RunPython(clear_course_level_schedule, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='weeks',
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='e.g. مجموعة السبت والثلاثاء', max_length=150)),
                ('mode', models.CharField(choices=[('group', 'جروب'), ('private', 'خصوصي')], default='group', max_length=10)),
                ('start_date', models.DateField(blank=True, help_text='First day sessions are generated from', null=True)),
                ('weeks', models.PositiveSmallIntegerField(default=8, help_text='How many weeks of sessions to generate', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='team.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.cohort'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cohort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.cohort'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('cohort', 'starts_at')},
        ),
        migrations.CreateModel(
            name='CohortSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)])),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courses.cohort')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('cohort', 'weekday', 'start_time')},
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.cohortslot'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseSlot',
        ),
    ]
