# Generated by Django 5.2.17 on 2026-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_start_date_remove_course_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AlterField(
            model_name='course',
            name='price_group',
            field=models.PositiveIntegerField(blank=True, help_text='EGP', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_private',
            field=models.PositiveIntegerField(blank=True, help_text='EGP', null=True),
        ),
    ]
