# Generated by Django 5.2.17 on 2026-10-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_level_alter_course_price_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='kind',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'مدرّس')], default='student', max_length=10),
        ),
    ]
