# Generated by Django 5.2.17 on 2026-10-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollmentrequest_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='payment_method',
            field=models.CharField(choices=[('online', 'دفع أونلاين'), ('contact', 'التواصل معي لترتيب الدفع')], default='contact', max_length=10),
        ),
    ]
