# Generated by Django 5.2.17 on 2026-10-05 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def confirm_existing(apps, schema_editor):
    """Groups that already have students or sessions are running: don't put them back into waiting."""
    from django.db.models import Q
    from django.utils import timezone
    Cohort = apps.get_model("courses", "Cohort")
    Cohort.objects.filter(confirmed_at__isnull=True).filter(
        Q(enrollments__isnull=False) | Q(lessons__isnull=False)).update(confirmed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_enrollmentrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_students',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cohort',
            name='min_students',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='courses.cohort'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('teacher_assigned', 'تم اختيار المدرس والمواعيد'), ('waiting', 'بانتظار اكتمال المجموعة'), ('enrolled', 'تم التسجيل في الكورس'), ('closed', 'مغلق')], default='new', max_length=20),
        ),
        migrations.RunPython(confirm_existing, migrations.RunPython.noop),
    ]
