# Generated by Django 5.2.17 on 2026-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_cohort_min_max_waiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offers_semi_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price_semi_private',
            field=models.PositiveIntegerField(blank=True, help_text='EGP', null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='mode',
            field=models.CharField(choices=[('group', 'Group'), ('semi_private', 'Semi private'), ('private', 'Private')], default='group', max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='mode',
            field=models.CharField(choices=[('group', 'Group'), ('semi_private', 'Semi private'), ('private', 'Private')], default='group', max_length=15),
        ),
    ]
