# Generated by Django 5.2.17 on 2026-09-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. A1, B2, C1', max_length=10, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_ar', models.TextField()),
                ('description_en', models.TextField()),
                ('duration_ar', models.CharField(max_length=100)),
                ('duration_en', models.CharField(max_length=100)),
                ('price_group', models.PositiveIntegerField(help_text='Price in EGP for group sessions')),
                ('price_private', models.PositiveIntegerField(help_text='Price in EGP for private sessions')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
    ]
