# Generated by Django 5.2.17 on 2026-09-24 15:27

import django.core.validators
from django.db import migrations, models


def equal_bands(apps, schema_editor):
    """Start with equal bands (0, 16, 33, 50, 66, 83 for six levels) — the same
    placement the test used before thresholds became editable."""
    Level = apps.get_model("levels", "Level")
    levels = list(Level.objects.order_by("order", "code"))
    for i, level in enumerate(levels):
        level.test_min_percent = i * 100 // len(levels)
        level.save(update_fields=["test_min_percent"])


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='test_min_percent',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Level test: minimum score (%) to be placed in this level. Empty = never assigned by the test.', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RunPython(equal_bands, migrations.RunPython.noop),
    ]
