# Generated by Django 5.2.17 on 2026-10-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_level_test_min_percent'),
        ('quiz', '0007_remove_placementresult_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
